export const icons = {
    atium: '/icons/atium.png',
    back: '/icons/back-button.png',
    clipboard: '/icons/clipboard.svg',
    close: '/icons/close-icon.png',
    github: '/icons/github-icon.svg',
    hamburgerMenu: '/icons/hamburger-icon.png',
    iceAndFire: '/icons/house-stark-sigil.png',
    stormlightArchive: '/icons/bridge-four.svg',
    wheelOfTime: '/icons/wheel-of-time.webp',
    moon: '/icons/moon.svg',
    sun: '/icons/sun.svg',
};

export const bookCovers = {
    aCrownOfSwords: '/book-covers/a-crown-of-swords.jpeg',
    aGameOfThrones: '/book-covers/a-game-of-thrones.jpeg',
    aLittleHatred: '/book-covers/a-little-hatred.jpg',
    aMemoryOfLight: '/book-covers/a-memory-of-light.jpeg',
    annaKarenina: '/book-covers/anna-karenina.jpg',
    ashesOfMan: '/book-covers/ashes-of-man.jpg',
    beforeTheyAreHanged: '/book-covers/before-they-are-hanged.jpg',
    bestServedCold: '/book-covers/best-served-cold.jpg',
    crossroadsOfTwilight: '/book-covers/crossroads-of-twilight.png',
    dawnshard: '/book-covers/dawnshard.jpg',
    demonInWhite: '/book-covers/demon-in-white.jpg',
    disquietGods: '/book-covers/disquiet-gods.jpg',
    dune: '/book-covers/dune.jpeg',
    duneMessiah: '/book-covers/dune-messiah.jpeg',
    elantris: '/book-covers/elantris.jpg',
    empireOfSilence: '/book-covers/empire-of-silence.jpg',
    eyeOfTheWorld: '/book-covers/eye-of-the-world.jpeg',
    heroOfAges: '/book-covers/hero-of-ages.webp',
    howlingDark: '/book-covers/howling-dark.jpg',
    hyperion: '/book-covers/hyperion.jpg',
    kingdomsOfDeath: '/book-covers/kingdoms-of-death.webp',
    knifeOfDreams: '/book-covers/knife-of-dreams.jpg',
    lastArgumentOfKings: '/book-covers/last-argument-of-kings.webp',
    lordOfChaos: '/book-covers/lord-of-chaos.png',
    mistborn: '/book-covers/mistborn.jpg',
    neuromancer: '/book-covers/neuromancer.jpg',
    newSpring: '/book-covers/new-spring.jpeg',
    oathbringer: '/book-covers/oathbringer.jpg',
    redCountry: '/book-covers/red-country.webp',
    shadowsOfSelf: '/book-covers/shadows-of-self.jpg',
    sharpEnds: '/book-covers/sharp-ends.jpg',
    theAlloyOfLaw: '/book-covers/the-alloy-of-law.jpg',
    theAnxiousGeneration: '/book-covers/the-anxious-generation.jpg',
    theBandsOfMourning: '/book-covers/the-bands-of-mourning.avif',
    theBladeItself: '/book-covers/the-blade-itself.jpg',
    theClosingOfTheAmericanMind: '/book-covers/the-closing-of-the-american-mind.png',
    theCoddlingOfTheAmericanMind: '/book-covers/the-coddling-of-the-american-mind.jpg',
    theDragonReborn: '/book-covers/the-dragon-reborn.jpeg',
    theDregsOfEmpire: '/book-covers/the-dregs-of-empire.png',
    theFallOfHyperion: '/book-covers/the-fall-of-hyperion.jpg',
    theFiresOfHeaven: '/book-covers/the-fires-of-heaven.jpg',
    theGatheringStorm: '/book-covers/the-gathering-storm.jpeg',
    theGreatHunt: '/book-covers/the-great-hunt.jpeg',
    theHeroes: '/book-covers/the-heroes.jpg',
    theMythicalManMonth: '/book-covers/the-mythical-man-month.png',
    thePathOfDaggers: '/book-covers/the-path-of-daggers.jpeg',
    theShadowRising: '/book-covers/the-shadow-rising.jpg',
    theTroubleWithPeace: '/book-covers/the-trouble-with-peace.jpeg',
    theWayOfKings: '/book-covers/the-way-of-kings.jpg',
    theWellOfAscension: '/book-covers/the-well-of-ascension.jpeg',
    theWisdomOfCrowds: '/book-covers/the-wisdom-of-crowds.webp',
    towersOfMidnight: '/book-covers/towers-of-midnight.jpeg',
    warbreaker: '/book-covers/warbreaker.jpeg',
    wintersHeart: '/book-covers/winters-heart.jpeg',
    wordsOfRadiance: '/book-covers/words-of-radiance.jpg',
};

export const bookPalettes = {
    aCrownOfSwords: (await import('@/lib/book-palettes/a-crown-of-swords.json')).palette,
    aGameOfThrones: (await import('@/lib/book-palettes/a-game-of-thrones.json')).palette,
    aLittleHatred: (await import('@/lib/book-palettes/a-little-hatred.json')).palette,
    aMemoryOfLight: (await import('@/lib/book-palettes/a-memory-of-light.json')).palette,
    annaKarenina: (await import('@/lib/book-palettes/anna-karenina.json')).palette,
    ashesOfMan: (await import('@/lib/book-palettes/ashes-of-man.json')).palette,
    beforeTheyAreHanged: (await import('@/lib/book-palettes/before-they-are-hanged.json')).palette,
    bestServedCold: (await import('@/lib/book-palettes/best-served-cold.json')).palette,
    crossroadsOfTwilight: (await import('@/lib/book-palettes/crossroads-of-twilight.json')).palette,
    dawnshard: (await import('@/lib/book-palettes/dawnshard.json')).palette,
    demonInWhite: (await import('@/lib/book-palettes/demon-in-white.json')).palette,
    disquietGods: (await import('@/lib/book-palettes/disquiet-gods.json')).palette,
    dune: (await import('@/lib/book-palettes/dune.json')).palette,
    duneMessiah: (await import('@/lib/book-palettes/dune-messiah.json')).palette,
    elantris: (await import('@/lib/book-palettes/elantris.json')).palette,
    empireOfSilence: (await import('@/lib/book-palettes/empire-of-silence.json')).palette,
    eyeOfTheWorld: (await import('@/lib/book-palettes/eye-of-the-world.json')).palette,
    heroOfAges: (await import('@/lib/book-palettes/hero-of-ages.json')).palette,
    howlingDark: (await import('@/lib/book-palettes/howling-dark.json')).palette,
    hyperion: (await import('@/lib/book-palettes/hyperion.json')).palette,
    kingdomsOfDeath: (await import('@/lib/book-palettes/kingdoms-of-death.json')).palette,
    knifeOfDreams: (await import('@/lib/book-palettes/knife-of-dreams.json')).palette,
    lastArgumentOfKings: (await import('@/lib/book-palettes/last-argument-of-kings.json')).palette,
    lordOfChaos: (await import('@/lib/book-palettes/lord-of-chaos.json')).palette,
    mistborn: (await import('@/lib/book-palettes/mistborn.json')).palette,
    neuromancer: (await import('@/lib/book-palettes/neuromancer.json')).palette,
    newSpring: (await import('@/lib/book-palettes/new-spring.json')).palette,
    oathbringer: (await import('@/lib/book-palettes/oathbringer.json')).palette,
    redCountry: (await import('@/lib/book-palettes/red-country.json')).palette,
    shadowsOfSelf: (await import('@/lib/book-palettes/shadows-of-self.json')).palette,
    sharpEnds: (await import('@/lib/book-palettes/sharp-ends.json')).palette,
    theAlloyOfLaw: (await import('@/lib/book-palettes/the-alloy-of-law.json')).palette,
    theAnxiousGeneration: (await import('@/lib/book-palettes/the-anxious-generation.json')).palette,
    theBandsOfMourning: (await import('@/lib/book-palettes/the-bands-of-mourning.json')).palette,
    theBladeItself: (await import('@/lib/book-palettes/the-blade-itself.json')).palette,
    theClosingOfTheAmericanMind: (await import('@/lib/book-palettes/the-closing-of-the-american-mind.json')).palette,
    theCoddlingOfTheAmericanMind: (await import('@/lib/book-palettes/the-coddling-of-the-american-mind.json')).palette,
    theDragonReborn: (await import('@/lib/book-palettes/the-dragon-reborn.json')).palette,
    theDregsOfEmpire: (await import('@/lib/book-palettes/the-dregs-of-empire.json')).palette,
    theFallOfHyperion: (await import('@/lib/book-palettes/the-fall-of-hyperion.json')).palette,
    theFiresOfHeaven: (await import('@/lib/book-palettes/the-fires-of-heaven.json')).palette,
    theGatheringStorm: (await import('@/lib/book-palettes/the-gathering-storm.json')).palette,
    theGreatHunt: (await import('@/lib/book-palettes/the-great-hunt.json')).palette,
    theHeroes: (await import('@/lib/book-palettes/the-heroes.json')).palette,
    theMythicalManMonth: (await import('@/lib/book-palettes/the-mythical-man-month.json')).palette,
    thePathOfDaggers: (await import('@/lib/book-palettes/the-path-of-daggers.json')).palette,
    theShadowRising: (await import('@/lib/book-palettes/the-shadow-rising.json')).palette,
    theTroubleWithPeace: (await import('@/lib/book-palettes/the-trouble-with-peace.json')).palette,
    theWayOfKings: (await import('@/lib/book-palettes/the-way-of-kings.json')).palette,
    theWellOfAscension: (await import('@/lib/book-palettes/the-well-of-ascension.json')).palette,
    theWisdomOfCrowds: (await import('@/lib/book-palettes/the-wisdom-of-crowds.json')).palette,
    towersOfMidnight: (await import('@/lib/book-palettes/towers-of-midnight.json')).palette,
    warbreaker: (await import('@/lib/book-palettes/warbreaker.json')).palette,
    wintersHeart: (await import('@/lib/book-palettes/winters-heart.json')).palette,
    wordsOfRadiance: (await import('@/lib/book-palettes/words-of-radiance.json')).palette,
} satisfies { [key: string]: string[] };

export const patterns = {
    shinyGold: '/patterns/shiny-gold.jpg',
    mist: '/patterns/mist2.png',
    sand: '/patterns/sand.jpg',
    highstorm: '/patterns/shallan.jpg',
    ironThrone: '/patterns/iron-throne.jpg',
    dragon: '/patterns/dragon-scales.jpg',
    nebula: '/patterns/nebula.jpg',
    needles: '/patterns/needles.jpg',
    sun: '/patterns/aia-0304.jpg',
    blood: '/patterns/bloody-handprint.jpg',
    paper: '/patterns/paper-texture-2.jpg',
};

export const gifs = {
    underConstruction: '/gifs/under-construction.gif',
};
