export const icons = {
    atium: '/icons/atium.png',
    back: '/icons/back-button.png',
    clipboard: '/icons/clipboard.svg',
    close: '/icons/close-icon.png',
    github: '/icons/github-icon.svg',
    hamburgerMenu: '/icons/hamburger-icon.png',
    iceAndFire: '/icons/house-stark-sigil.png',
    stormlightArchive: '/icons/bridge-four.svg',
    wheelOfTime: '/icons/wheel-of-time.webp',
    moon: '/icons/moon.svg',
    sun: '/icons/sun.svg',
};

export const bookCovers = {
    aCrownOfSwords: '/book-covers/a-crown-of-swords.jpeg',
    aGameOfThrones: '/book-covers/a-game-of-thrones.jpeg',
    aLittleHatred: '/book-covers/a-little-hatred.jpg',
    aMemoryOfLight: '/book-covers/a-memory-of-light.jpeg',
    annaKarenina: '/book-covers/anna-karenina.jpg',
    ashesOfMan: '/book-covers/ashes-of-man.jpg',
    beforeTheyAreHanged: '/book-covers/before-they-are-hanged.jpg',
    bestServedCold: '/book-covers/best-served-cold.jpg',
    crossroadsOfTwilight: '/book-covers/crossroads-of-twilight.png',
    dawnshard: '/book-covers/dawnshard.jpg',
    demonInWhite: '/book-covers/demon-in-white.jpg',
    disquietGods: '/book-covers/disquiet-gods.jpg',
    dune: '/book-covers/dune.jpeg',
    duneMessiah: '/book-covers/dune-messiah.jpeg',
    elantris: '/book-covers/elantris.jpg',
    empireOfSilence: '/book-covers/empire-of-silence.jpg',
    eyeOfTheWorld: '/book-covers/eye-of-the-world.jpeg',
    heroOfAges: '/book-covers/hero-of-ages.webp',
    howlingDark: '/book-covers/howling-dark.jpg',
    hyperion: '/book-covers/hyperion.jpg',
    kingdomsOfDeath: '/book-covers/kingdoms-of-death.webp',
    knifeOfDreams: '/book-covers/knife-of-dreams.jpg',
    lastArgumentOfKings: '/book-covers/last-argument-of-kings.webp',
    lordOfChaos: '/book-covers/lord-of-chaos.png',
    mistborn: '/book-covers/mistborn.jpg',
    neuromancer: '/book-covers/neuromancer.jpg',
    newSpring: '/book-covers/new-spring.jpeg',
    oathbringer: '/book-covers/oathbringer.jpg',
    redCountry: '/book-covers/red-country.webp',
    shadowsOfSelf: '/book-covers/shadows-of-self.jpg',
    sharpEnds: '/book-covers/sharp-ends.jpg',
    theAlloyOfLaw: '/book-covers/the-alloy-of-law.jpg',
    theAnxiousGeneration: '/book-covers/the-anxious-generation.jpg',
    theBandsOfMourning: '/book-covers/the-bands-of-mourning.avif',
    theBladeItself: '/book-covers/the-blade-itself.jpg',
    theClosingOfTheAmericanMind: '/book-covers/the-closing-of-the-american-mind.png',
    theCoddlingOfTheAmericanMind: '/book-covers/the-coddling-of-the-american-mind.jpg',
    theDragonReborn: '/book-covers/the-dragon-reborn.jpeg',
    theDregsOfEmpire: '/book-covers/the-dregs-of-empire.png',
    theFallOfHyperion: '/book-covers/the-fall-of-hyperion.jpg',
    theFiresOfHeaven: '/book-covers/the-fires-of-heaven.jpg',
    theGatheringStorm: '/book-covers/the-gathering-storm.jpeg',
    theGreatHunt: '/book-covers/the-great-hunt.jpeg',
    theHeroes: '/book-covers/the-heroes.jpg',
    theMythicalManMonth: '/book-covers/the-mythical-man-month.png',
    thePathOfDaggers: '/book-covers/the-path-of-daggers.jpeg',
    theShadowRising: '/book-covers/the-shadow-rising.jpg',
    theTroubleWithPeace: '/book-covers/the-trouble-with-peace.jpeg',
    theWayOfKings: '/book-covers/the-way-of-kings.jpg',
    theWellOfAscension: '/book-covers/the-well-of-ascension.jpeg',
    theWisdomOfCrowds: '/book-covers/the-wisdom-of-crowds.webp',
    towersOfMidnight: '/book-covers/towers-of-midnight.jpeg',
    warbreaker: '/book-covers/warbreaker.jpeg',
    wintersHeart: '/book-covers/winters-heart.jpeg',
    wordsOfRadiance: '/book-covers/words-of-radiance.jpg',
};

export const patterns = {
    shinyGold: '/patterns/shiny-gold.jpg',
    mist: '/patterns/mist2.png',
    sand: '/patterns/sand.jpg',
    highstorm: '/patterns/shallan.jpg',
    ironThrone: '/patterns/iron-throne.jpg',
    dragon: '/patterns/dragon-scales.jpg',
    nebula: '/patterns/nebula.jpg',
    needles: '/patterns/needles.jpg',
    sun: '/patterns/aia-0304.jpg',
    blood: '/patterns/bloody-handprint.jpg',
};

export const gifs = {
    underConstruction: '/gifs/under-construction.gif',
};
